### ISSUE TITLE
Search path animation not correct.

### ISSUE THREAD

**Issue by Silvernitro** [Silvernitro/pathfinding_visualizer#11]
1.  Currently, it looks like Dijkstra's Algorithm is searching the grid row by row. I'm not sure, but that doesn't seem to be the correct way Dijkstra's Algorithm should work. Maybe it's because we have no weights yet. We might wanna relook at our implementation of Dijkstra's in the meantime too.

2. The animation for the search path seems to get slow after a certain number of nodes for me. It might be because we are still running `npm start` in development mode instead of building the app with `npm run build`. Might also just be my computer.

**Comment by Puzzleeee** [comment]
First issue has been fixed, caused by an error in the sorting of the priority queue used in the implementation of Dijkstra's Algorithm.
